export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const REMOVELISTING_REQUEST = 'REMOVELISTING_REQUEST';
export const REMOVELISTING_SUCCESS = 'REMOVELISTING_SUCCESS';
export const REMOVELISTING_FAILURE = 'REMOVELISTING_FAILURE'; 

export const REMOVE_RENTED_ITEM = 'REMOVE_RENTED_ITEM';

export const ADDLISTING_REQUEST = 'ADDLISTING_REQUEST';
export const ADDLISTING_SUCCESS = 'ADDLISTING_SUCCESS';
export const ADDLISTING_FAILURE = 'ADDLISTING_FAILURE';

export const UI_TOGGLE_VIEW_MANAGEDLISTING = 'UI_TOGGLE_VIEW_MANAGEDLISTING';
export const UI_TOGGLE_VIEW_ADDNEWLISTINGFORM = 'UI_TOGGLE_VIEW_ADDNEWLISTINGFORM';
export const UI_UPDATE_FORMFIELD = 'UI_UPDATE_FORMFIELD';


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const VERIFY_USER = 'VERIFY_USER';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
// Assuming logout op is always successful.
export const LOGOUT = 'LOGOUT';
