export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// Assuming logout op is always successful. 
export const LOGOUT = 'LOGOUT'; 

export const REMOVELISTING_REQUEST = 'REMOVELISTING_REQUEST';
export const REMOVELISTING_SUCCESS = 'REMOVELISTING_SUCCESS';
export const REMOVELISTING_FAILURE = 'REMOVELISTING_FAILURE'; 

export const REMOVE_RENTED_ITEM = 'REMOVE_RENTED_ITEM';

export const UI_TOGGLE_VIEW_MANAGEDLISTING = 'UI_TOGGLE_VIEW_MANAGEDLISTING';
export const UI_TOGGLE_VIEW_ADDNEWLISTINGFORM = 'UI_TOGGLE_VIEW_ADDNEWLISTINGFORM';

